//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuneralWebsite.CalendarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalendarService.ICalendarServices")]
    public interface ICalendarServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarServices/CheckDayAvailability", ReplyAction="http://tempuri.org/ICalendarServices/CheckDayAvailabilityResponse")]
        int CheckDayAvailability(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarServices/ReserveDay", ReplyAction="http://tempuri.org/ICalendarServices/ReserveDayResponse")]
        int ReserveDay(string date, string personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarServices/GetAllReservationsBetweenDates", ReplyAction="http://tempuri.org/ICalendarServices/GetAllReservationsBetweenDatesResponse")]
        string GetAllReservationsBetweenDates(string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarServices/DeleteAllData", ReplyAction="http://tempuri.org/ICalendarServices/DeleteAllDataResponse")]
        void DeleteAllData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalendarServicesChannel : FuneralWebsite.CalendarService.ICalendarServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalendarServicesClient : System.ServiceModel.ClientBase<FuneralWebsite.CalendarService.ICalendarServices>, FuneralWebsite.CalendarService.ICalendarServices {
        
        public CalendarServicesClient() {
        }
        
        public CalendarServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalendarServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckDayAvailability(string date) {
            return base.Channel.CheckDayAvailability(date);
        }
        
        public int ReserveDay(string date, string personID) {
            return base.Channel.ReserveDay(date, personID);
        }
        
        public string GetAllReservationsBetweenDates(string startDate, string endDate) {
            return base.Channel.GetAllReservationsBetweenDates(startDate, endDate);
        }
        
        public void DeleteAllData() {
            base.Channel.DeleteAllData();
        }
    }
}
