//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuneralWebsite.SaveFuneral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaveFuneral.EulogyServices")]
    public interface EulogyServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EulogyServices/getAllEulogys", ReplyAction="http://tempuri.org/EulogyServices/getAllEulogysResponse")]
        string getAllEulogys(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EulogyServices/getEulogy", ReplyAction="http://tempuri.org/EulogyServices/getEulogyResponse")]
        string getEulogy(string userName, string nameOfDeceased);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EulogyServices/makeOrEditEulogy", ReplyAction="http://tempuri.org/EulogyServices/makeOrEditEulogyResponse")]
        string makeOrEditEulogy(string userName, string nameOfDeceased, string eulogy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EulogyServicesChannel : FuneralWebsite.SaveFuneral.EulogyServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EulogyServicesClient : System.ServiceModel.ClientBase<FuneralWebsite.SaveFuneral.EulogyServices>, FuneralWebsite.SaveFuneral.EulogyServices {
        
        public EulogyServicesClient() {
        }
        
        public EulogyServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EulogyServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EulogyServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EulogyServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAllEulogys(string userName) {
            return base.Channel.getAllEulogys(userName);
        }
        
        public string getEulogy(string userName, string nameOfDeceased) {
            return base.Channel.getEulogy(userName, nameOfDeceased);
        }
        
        public string makeOrEditEulogy(string userName, string nameOfDeceased, string eulogy) {
            return base.Channel.makeOrEditEulogy(userName, nameOfDeceased, eulogy);
        }
    }
}
