//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuneralWebsite.AWeirdPricingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AWeirdPricingService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJesus", ReplyAction="http://tempuri.org/IService1/GetJesusResponse")]
        string GetJesus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRate", ReplyAction="http://tempuri.org/IService1/getRateResponse")]
        double getRate(int funeral_type, int cas_type, int flowers, bool discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getOnThisDay", ReplyAction="http://tempuri.org/IService1/getOnThisDayResponse")]
        string getOnThisDay(int month, int day);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FuneralWebsite.AWeirdPricingService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FuneralWebsite.AWeirdPricingService.IService1>, FuneralWebsite.AWeirdPricingService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetJesus() {
            return base.Channel.GetJesus();
        }
        
        public double getRate(int funeral_type, int cas_type, int flowers, bool discount) {
            return base.Channel.getRate(funeral_type, cas_type, flowers, discount);
        }
        
        public string getOnThisDay(int month, int day) {
            return base.Channel.getOnThisDay(month, day);
        }
    }
}
